export const initialData = {
  coord: { lon: 96.1561, lat: 16.8053 },
  weather: [
    { id: 804, main: "Clouds", description: "overcast clouds", icon: "04d" },
  ],
  base: "stations",
  main: {
    temp: 301.13,
    feels_like: 307.55,
    temp_min: 301.13,
    temp_max: 301.13,
    pressure: 1006,
    humidity: 94,
  },
  visibility: 5000,
  wind: { speed: 4.63, deg: 150 },
  clouds: { all: 100 },
  dt: 1687856073,
  sys: {
    type: 1,
    id: 9322,
    country: "MM",
    sunrise: 1687820665,
    sunset: 1687867918,
  },
  timezone: 23400,
  id: 1298824,
  name: "Yangon",
  cod: 200,
};

export const popularCities = [
  "Tokyo",
  "Delhi",
  "Shanghai",
  "São Paulo",
  "Mumbai",
  "Beijing",
  "Cairo",
  "Dhaka",
  "Mexico City",
  "Osaka",
  "Karachi",
  "Chongqing",
  "Istanbul",
  "Buenos Aires",
  "Mandalay",
  "Kolkata",
  "Lagos",
  "Kinshasa",
  "Manila",
  "Rio de Janeiro",
  "Guangzhou",
  "Los Angeles",
  "Shenzhen",
  "Moscow",
  "Lahore",
  "Bangalore",
  "Jakarta",
  "London",
  "Lima",
  "Bangkok",
  "Pyin Oo Lwin",
  "Chennai",
  "New York City",
  "Chengdu",
  "Nairobi",
  "Hong Kong",
  "Ho Chi Minh City",
  "Hyderabad",
  "Ahmedabad",
  "Kuala Lumpur",
  "Tehran",
  "Bogotá",
  "Riyadh",
  "Santiago",
  "Alexandria",
  "Sydney",
  "Wuhan",
  "Melbourne",
  "Buenos Aires",
  "Madrid",
  "Pune",
  "Johannesburg",
  "Kabul",
  "Berlin",
  "Rome",
  "Hanoi",
  "Baghdad",
  "Riyadh",
  "Singapore",
  "Ankara",
  "Santiago",
  "Abu Dhabi",
  "Budapest",
  "Vienna",
  "Athens",
  "Amsterdam",
  "Prague",
  "Stockholm",
  "Zurich",
  "Warsaw",
  "Oslo",
  "Helsinki",
  "Brussels",
  "Copenhagen",
  "Lisbon",
  "Dublin",
  "Bucharest",
  "Reykjavik",
  "Oslo",
  "Helsinki",
  "Stockholm",
  "Bern",
  "Copenhagen",
  "Warsaw",
  "Brussels",
  "Prague",
  "Vienna",
  "Budapest",
  "Athens",
  "Sofia",
  "Zagreb",
  "Dublin",
  "Lisbon",
  "Bucharest",
  "Belgrade",
  "Helsinki",
  "Vilnius",
  "Riga",
  "Tallinn",
  "Valletta",
  "Warsaw",
  "Prague",
  "Yangon",
];
