export const myDatas = [
  {
    id: 0,
    type: "snack",
    name: "humberger",
    source: "/src/items/1.jpg",
    value: 2500,
    addToCart: false,
  },
  {
    id: 1,
    type: "fruit",
    name: "straw berry",
    source: "/src/items/strawB.jpg",
    value: 2500,
    addToCart: false,
  },
  {
    id: 2,
    type: "beverage",
    name: "beer",
    source: "/src/items/2.jpg",
    value: 2600,
    addToCart: false,
  },
  {
    id: 3,
    type: "fruit",
    name: "red apple",
    source: "/src/items/3.jpg",
    value: 300,

    addToCart: false,
  },
  {
    id: 4,
    type: "cake",
    name: "chocolate cake",
    source: "/src/items/4.jpg",
    value: 5000,
    addToCart: false,
  },
  {
    id: 5,
    type: "fruit",
    name: "green apple",
    source: "/src/items/5.jpg",
    value: 400,

    addToCart: false,
  },
  {
    id: 6,
    type: "pizza",
    name: "flavoured pizza",
    source: "/src/items/6.jpg",
    value: 9000,
    addToCart: false,
  },
  {
    id: 7,
    type: "fruit",
    name: "banana",
    source: "/src/items/banana.jpg",
    value: 500,

    addToCart: false,
  },
  {
    id: 8,
    type: "snack",
    name: "bread",
    source: "/src/items/bread.jpg",
    value: 1000,
    addToCart: false,
  },
  {
    id: 9,
    type: "snack",
    name: "bread baked",
    source: "/src/items/bread1.jpg",
    value: 1400,
    addToCart: false,
  },
  {
    id: 10,
    type: "snack",
    name: "donut",
    source: "/src/items/donut.jpg",
    value: 1500,
    addToCart: false,
  },
  {
    id: 11,
    type: "snack",
    name: "donut",
    source: "/src/items/donutTriple.jpg",
    value: 1500,
    addToCart: false,
  },
  {
    id: 12,
    type: "hat",
    name: "style hat",
    source: "/src/items/hat1.jpg",
    value: 1500,
    addToCart: false,
  },
  {
    id: 13,
    type: "hat",
    name: "black hat",
    source: "/src/items/hatb.jpg",
    value: 1500,
    addToCart: false,
  },
  {
    id: 14,
    type: "hat",
    name: "hat",
    source: "/src/items/hatw.jpg",
    value: 1500,
    addToCart: false,
  },
  {
    id: 15,
    type: "hat",
    name: "Los hat",
    source: "/src/items/headLa.jpg",
    value: 1500,
    addToCart: false,
  },
  {
    id: 16,
    type: "hat",
    name: "Nike hat",
    source: "/src/items/headNike.jpg",
    value: 1500,
    addToCart: false,
  },
  {
    id: 17,
    type: "fruit",
    name: "lemon",
    source: "/src/items/lemon.jpg",
    value: 1500,
    addToCart: false,
  },
  {
    id: 18,
    type: "beverage",
    name: "pepsi",
    source: "/src/items/pepsi.jpg",
    value: 1500,
    addToCart: false,
  },
  {
    id: 19,
    type: "beverage",
    name: "caned pepsi",
    source: "/src/items/pepsi1.jpg",
    value: 3000,
    addToCart: false,
  },
  {
    id: 20,
    type: "pizza",
    name: "omalet pizza",
    source: "/src/items/pizz.jpg",
    value: 2400,
    addToCart: false,
  },
  {
    id: 21,
    type: "cake",
    name: "pile cake",
    source: "/src/items/snackS.jpg",
    value: 4000,
    addToCart: false,
  },
];
export const alphabet = [
  "A",
  "B",
  "C",
  "D",
  "E",
  "F",
  "G",
  "H",
  "I",
  "J",
  "K",
  "L",
  "M",
  "N",
  "O",
  "P",
  "Q",
  "R",
  "S",
  "T",
  "U",
  "V",
  "W",
  "X",
  "Y",
  "Z",
];

export const user_datas = [
  {
    user_id: 0,
    user_name: "yami",
    email: "yami@gmail.com",
    password: "YAMI",
    address: "yamistreet",
    phone_number: "09425446711",
    profile_picture: "/src/svgs/1.svg",
  },
  {
    user_id: 1,
    user_name: "red",
    email: "red@gmail.com",
    password: "RED",
    address: "yamistreet",
    phone_number: "09425446711",
    profile_picture: "/src/svgs/1.svg",
  },
  {
    user_id: 2,
    user_name: "blue",
    email: "blue@gmail.com",
    password: "BLUE",
    address: "yamistreet",
    phone_number: "09425446711",
    profile_picture: "/src/svgs/1.svg",
  },
];

export const profileSvgs = [
  "/src/svgs/1.svg",
  "/src/svgs/2.svg",
  "/src/svgs/3.svg",
  "/src/svgs/4.svg",
  "/src/svgs/5.svg",
  "/src/svgs/6.svg",
  "/src/svgs/7.svg",
  "/src/svgs/8.svg",
  "/src/svgs/9.svg",
];
